# fly.toml app configuration file generated for linebotweb on 2023-12-14T15:02:37+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linebotweb"
primary_region = "sjc"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
